### ISSUE TITLE
question

### ISSUE THREAD

**Issue by saman749** [max-sn/robotarm#3]
Hi, I have a question more than an issue. How do you change the variable names in the figure from $a$ or $q$ to something else?

**Comment by max-sn** [comment]
Hi, you can change the names globally (or in a scope) with `\robotarmset{labels={a=<link length label>, q=<joint angle label>}}`. To change it for a specific link or joint you can use for example `\robotArm[labels={a1=<link length label of link 1>,q2=<joint angle label of joint 2>}]{2}`. This is currently undocumented behavior, because I'm not entirely satisfied with the implementation. I hope this is sufficient for now?

**Comment by saman749** [comment]
Great! thanks. 
I think it is a very nice package and can cover lots of cases for the course I'm teaching. I appreciate it.
